name: Cache Workflow

description: This is a cache dependency Workflow

inputs:
  caching:
    description: This should be a cache dependency
    default: 'true'
    required: false
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: cache-dep-${{ hashFiles('**/package-lock.json')}}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
