name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: node:16
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build artifacts
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-file
          path: dist

  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      artifact: "dist-file"

  result:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Outputs
        run: echo "${{needs.deploy.outputs.result}}"

  report:
    runs-on: ubuntu-latest
    needs: test
    if: failure() && needs.test.result == 'failure'
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report-file
          path: report.json
