name: Reusable Wrokflow

on:
  workflow_call:
    inputs:
      artifact:
        description: this is name of artifact
        required: true
        default: dist
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Downloaded artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact}}
          
      - name: Deploy code
        run: echo "Deploying..."
